### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by datamuc** [sj26/mailcatcher#210] opened 2015-03-05 14:48 UTC
Hi,

it seams that mailcatcher leaks a lot of memory. I've started it, and just reloading the page (without any mails in it) adds about 500kB to the process size:

    $ sv restart ./service/mailcatcher
    ok: run: ./service/mailcatcher: (pid 22424) 0s
    $ ps auxww | grep [m]ailcatcher # after each reload
    danielt  22424 33.3  4.5 135972 47032 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424 15.0  4.8 140292 49736 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  9.8  4.8 140700 49980 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  7.7  4.9 141268 50508 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  6.5  4.9 141700 51036 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  5.1  5.0 142260 51564 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  4.4  5.0 142676 52092 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  4.0  5.1 143220 52620 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080
    danielt  22424  3.7  5.1 143780 53124 ?        Sl   15:44   0:01 /home/danielt/.rvm/rubies/ruby-2.1.0/bin/ruby /home/danielt/.rvm/gems/ruby-2.1.0/bin/mailcatcher --foreground --smtp-ip 0.0.0.0 --http-port 4080

As you can see something around 500kB is added after each request to the RSS.

**Comment by Muffinman** [comment] 2015-03-10 12:58
Yeah I have to restart Mailcatcher every few days after it fills my entire RAM. Great app but slightly annoying!

**Comment by granbebe** [comment] 2015-03-23 17:10
I have the exact same issue with a little bit more of impacts.
I use mailcatcher on a test server. I have Apache in front to prevent a free access from anyone.
And mailcatcher consumes RAM every second without me doing anything.

**Comment by DrRoach** [comment] 2015-03-24 14:09
Yep getting the exact same issue here using cent OS

**Comment by alexbowers-tecmark** [comment] 2015-03-24 14:09
And on ubuntu

**Comment by fruit** [comment] 2015-03-26 09:28
+1 (CentOS 6.6), installed on VirtualBox via [puphpet.com](https://puphpet.com/#mail) site.

**Comment by alexbowers** [comment] 2015-03-30 15:32
![image](https://cloud.githubusercontent.com/assets/842974/6899757/565fbe42-d6fa-11e4-8d78-770fd6317bbd.png)

**Comment by alexbowers** [comment] 2015-03-30 15:33
These are both the same process - One is the parent of the other, but the point is, it is using 48% of my memory.

**Comment by derekjkeller** [comment] 2015-03-30 17:47
:+1:

**Comment by alexbowers** [comment] 2015-04-01 08:12
Still getting continually worse; doesn't seem to have an upper limit on the memory it uses (I guess until it crashes?)

![image](https://cloud.githubusercontent.com/assets/842974/6936924/40085cca-d84f-11e4-9e03-477f412f5c33.png)

**Comment by alexbowers** [comment] 2015-04-01 22:50
@sj26 Any input on this please? Or maybe guidance as to where the issue may lie so someone can look into it?

**Comment by sj26** [comment] 2015-04-01 23:39
Unfortunately Ruby has a habit of leaking memory. In-memory SQLite and EventMachine probably just complicates the whole situation.

Given mailcatcher is intended to be a development tool, and not necessarily running _all the time_ this is enough for me. If you'd like to attack it with perftools then patches are welcome!

**Comment by sj26** [comment] 2015-04-01 23:41
If you'd like something with a better resource profile, there's also [MailHog](https://github.com/mailhog/MailHog).

**Comment by alexbowers** [comment] 2015-04-02 08:13
@sj26 We are running this on a CI machine, and so running all the time is sort of a requirement (though I  guess we could force restart every day or something).

**Comment by jekakm** [comment] 2015-04-27 07:50
@sj26 But many people use it inside docker containers. For example: we have automated system, that runs stagings for our projects inside docker containers. And I have situation when 4 containers fill all memory cause mailcatcher

**Comment by pierre-pretorius** [comment] 2015-05-12 15:33
We use this gem on our QA server with foreman/upstart.  After it runs a few days it uses 2gb+ memory with about 20 mails.  It's actually the most memory consumption I've seen in all Ruby apps I've ran.  I agree it's a development tool, would be pretty awesome as a general tool too though.  For now we will add a cron daily restart.

**Comment by teknull** [comment] 2015-06-02 19:40
Having the same problem in OS X.  Noticed mailcatcher was running for two days with no activity and consumed approximately 2.8GB.  Had to kill it and restart.  Not a huge problem but would be nice if it didn't leak.

**Comment by maccman** [comment] 2015-06-09 01:02
We're seeing a huge memory leak too. I don't think it can be explained away by "ruby is bad with memory".

**Comment by sj26** [comment] 2015-06-09 01:07
I'm not seeing a huge impact locally. If you folks would like to provide some profiling information to identify the source I'll happily address it.

**Comment by shakycode** [comment] 2015-06-29 12:56
Has anyone been able to provide any useful data for @sj26?  Mailcatcher is causing Ruby to bloat to nearly 3GB if I leave it running.  I'm to the point now where I run a cron job on my macbook to kill and restart it every 12 hours to kill the leak.

**Comment by DrRoach** [comment] 2015-06-29 14:37
@shakycode Unfortunately I don't know ruby so I can't provide any in code info all I can offer are the images that I posted further up that showed mailcatcher using 42% of a 2GB servers' memory after an hour.

**Comment by igneus** [comment] 2015-07-15 19:01
Which ruby version(s) is the memory-leak experienced on? I am trying hard to reproduce it, but without success.

**Comment by alexbowers** [comment] 2015-07-15 19:48
1.9 and 2/1

**Comment by alexbowers** [comment] 2015-07-15 19:48
Just leave it in the background unused for about 2 days. I did mine in a vagrant machine.

**Comment by shakycode** [comment] 2015-07-15 19:54
I'm on 1.9.3 and 2.1.1 and I see the memory leaks too.  I haven't tried installing it against 2.2.2 which has better GC.  But mailcatcher is definitely leaking..

**Comment by igneus** [comment] 2015-07-15 20:37
Thanks.

Concerning leaving for two days: I hoped I would be able to reproduce the "+500kB per page refresh" scenario described by @datamuc - it would be much easier to debug.

**Comment by alexbowers** [comment] 2015-07-15 21:39
Ah, i never refreshed the page, or sent emails to it. just it running in the background caused it to use a significant part of memory up. Sorry i cant pin it down more than that
If you have anything that i can use on my machine to track ruby memory usage or whatever ill install it to help you out, but other than that, im not going to be much help im afraid.

**Comment by datamuc** [comment] 2015-07-16 04:12
Hi,

    $ mailcatcher --version
    mailcatcher 0.6.1
    $ ruby -v
    ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]

**Comment by perk11** [comment] 2015-07-19 23:44
Also experiencing this:

    $ mailcatcher --version
    mailcatcher 0.6.1
    $ ruby -v
    ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by sj26** [comment] 2015-07-19 23:51
Here are some memory profiling tools:

https://github.com/SamSaffron/memory_profiler
https://github.com/ruby-prof/ruby-prof

If you can run mailcatcher in the foreground using these tools and replicate the memory issues with profiling data then maybe we can figured out what's causing it and fix it. I don't see a lot of unexpected memory use when I use it, but will try and replicate as well.

**Comment by infabo** [comment] 2015-07-22 15:12
Jep.
Windows 8.1, Ruby 2.2.1 and this leak is HUGE! It filled up my machine with 16GB of RAM - completely! Windows actually started closing applications just to keep up....until I found out in task manager that ruby.exe just had allocated several GIGS of my RAM.....

**Comment by jaybeaton** [comment] 2015-07-30 14:34
I'm seeing this on a Mac, as well.  It was using 3GB of memory after several days.

```
$ mailcatcher --version
mailcatcher 0.6.1
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by datamuc** [comment] 2015-07-30 14:39
I have played with memory_profiler a bit:

<https://gist.github.com/datamuc/168e9266044ca3e30f96>

**Comment by SkylerRogers** [comment] 2015-10-06 13:29
Confirmed on mailcatcher version 0.6.1 (running on Ruby version 2.1.2p95 via Mac OS X Yosemite)

**Comment by davidchua** [comment] 2015-10-07 11:32
I'm on 0.6.1 (Ruby 2.2.0 Linuxmint Rebecca) and I've also noticed a high memory usage even though I'm not actively using it.

Mailcatcher only have been opened for a couple of days in the background

```
# smem output
$ smem -s swap
27148 davidc   ruby /home/davidc/.rvm/gems     1.7G   355.7M   355.7M   355.9M 
```
```
# ps grepping
27148 davidc   ruby /home/davidc/.rvm/gems     1.7G   355.7M   355.7M   355.9M 
davidc@grimlock-home ~/.local/share/Steam/steamapps/common  $ ps auwx | grep 27148
davidc   27148  0.0  4.4 2338128 364432 ?      Sl   Oct02   3:35 ruby /home/davidc/.rvm/gems/ruby-2.2.0/bin/mailcatcher   
```

**Comment by alexbowers** [comment] 2015-10-07 23:07
At this point, it looks like it wont be fixed.

I'd recommend going to Mailtrap.io, the free version should suit you perfectly for most needs. It does us quite well, and is reasonably easy to setup.

**Comment by sj26** [comment] 2015-10-07 23:39
@alexbowers sorry, as I've mentioned above I can't replicate this and nobody is contributing useful data with the suggested tools. Mailtrap seems reasonable for a hosted option. [MailHog](https://github.com/mailhog/MailHog) is another good alternative written in Go and locally hosted like mailcatcher.

**Comment by opensourceame** [comment] 2015-10-08 07:30
It would be a nice gesture to add a warning about this memory problem to the caveats section of the readme. I'm sure I'm not the first person to install this useful tool across a whole lot of development servers only to discover much later that it's killing the machines. It would nice to be forewarned about such a situation.

Of course we wouldn't want to discourage people from using the gem so the warning could be worded something like:

"In some situations mailcatcher is can consume a lot of memory. We advise you to monitor the process and restart it at regular intervals."

**Comment by Chronial** [comment] 2015-10-15 16:29
@sj26 I'm getting this issue on a fresh vagrant box based on `ubuntu/trusty64`, with just
```apt-get install -y ruby-dev libsqlite3-dev
gem install mailcatcher --no-ri --no-rdoc
mailcatcher --http-ip=0.0.0.0```

**Comment by derekjkeller** [comment] 2015-10-15 20:04
chronial's right -- pretty easy to reproduce this behavior using that box and those commands.

**Comment by Vincent--** [comment] 2015-10-28 14:21
+1

**Comment by junxy** [comment] 2015-10-30 02:00
Up 42 hours, memory: `789 MB` on docker

**Comment by aarnaud** [comment] 2015-11-16 14:40
Up
Ubuntu 14.04
mailcatcher 0.6.1
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by Chronial** [comment] 2015-11-16 14:44
For anybody who needs a solution to this *now*: Have a look at [mailhog](https://github.com/mailhog/MailHog) – it provides the same functionality. They offer [precompiled releases](https://github.com/mailhog/MailHog/releases) for basically any system.

Mailhog does not daemonize itself like mailcatcher. You should start it via init.d/systemd/supervisord. But if you're lazy like me, you can also do `nohup mailhog > /dev/null 2>&1 &`.

**Comment by aarnaud** [comment] 2015-11-16 14:53
Or MailDev  https://github.com/djfarrelly/MailDev

**Comment by jsirex** [comment] 2015-11-24 09:14
Looks like this one doesn't leak:
```
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
mailcatcher (0.5.12)
```

And this does:
```
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux
mailcatcher (0.6.1)

**Comment by sj26** [comment] 2015-11-24 09:15
Yes, it's probably an eventmachine leak.

**Comment by tsakamiya** [comment] 2015-11-27 07:49
I've try update  eventmachine to 1.0.8 and it works fine for me.

**Comment by CloCkWeRX** [comment] 2015-12-14 00:41
#586 seems a possible cause

**Comment by shakycode** [comment] 2015-12-14 00:47
Awesome that we're able to see a possible leak finally.

**Closed** 2015-12-14 02:54 UTC
