### ISSUE TITLE
Mail catching smtp timeout when running in background

### ISSUE THREAD

**Issue by istvano** [sj26/mailcatcher#182] opened 2014-12-22 12:49 UTC
Hi Guys,

I have a very strange issue but I do not how I could debug it any further.

1, if I run mailcatcher in the foreground -f -v 

a, web interface works perfectly
b, smtp receives emails flawlessly 

2, if I run it in the backgroud

a, web interface works
b, smtp interface does not respond.

Dec 22 12:34:24 sendemail[10247]: ERROR => Timeout while reading from localhost:2525 There was no response after 60 seconds.

If I want to telnet into it I CAN!

It is not a port issue as I run the test on the same computer and when it is in foreground mode it works.

I do not see any error logs anywhere. is there a way to enable some debug mode so that I can see why the smtp timeouts ?

Any idea what can be wrong ? 

my ruby version is -> ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
my mailcatcher version is mailcatcher (0.5.12)

My local gems:
*** LOCAL GEMS ***

activesupport (3.2.19)
bigdecimal (1.1.0)
builder (3.2.2)
bundler (1.5.3)
chef (11.16.4)
chef-zero (2.2)
coderay (1.1.0)
daemons (1.1.9)
diff-lcs (1.2.5)
docile (1.1.5)
erubis (2.7.0)
eventmachine (1.0.4)
ffi (1.9.5)
ffi-yajl (1.1.0)
haml (4.0.6)
hashie (2.1.2)
highline (1.6.21)
i18n (0.6.11)
io-console (0.3)
ipaddress (0.8.0)
json (1.8.1, 1.5.5)
libyajl2 (1.0.1)
mail (2.6.3)
mailcatcher (0.5.12)
method_source (0.8.2)
mime-types (1.25.1)
minitest (2.5.1)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0)
mixlib-config (2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (1.6.0)
multi_json (1.10.1)
mysql (2.9.1)
net-ssh (2.9.1)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.0)
ohai (7.4.0)
plist (3.1.0)
pry (0.10.1)
rack (1.5.2)
rack-protection (1.5.3)
rake (10.1.1, 0.9.2.2)
rdoc (3.9.5)
rest-client (1.6.7)
rspec (2.14.1)
rspec-core (2.14.8)
rspec-expectations (2.14.5)
rspec-mocks (2.14.6)
rspec_junit_formatter (0.1.6)
ruby-shadow (2.3.4)
simplecov (0.9.1)
simplecov-html (0.8.0)
sinatra (1.4.5)
skinny (0.2.3)
slop (3.6.0)
sqlite3 (1.3.10)
systemu (2.6.4)
thin (1.5.1)
tilt (1.4.1)
wmi-lite (1.0.0)

**Comment by Soullivaneuh** [comment] 2015-01-02 13:40
Exactly the same problem, and workaround.

In addition, if you run mailcatcher as daemon and try to quit from the interface, this will redirect you to mailcatcher homepage but won't kill the concerned process.

**Comment by soulim** [comment] 2015-01-04 00:18
Just got the same issue, and seems like it somehow depends on Ruby version.

The mailcatcher as a daemon doesn't work on Ruby `2.1.5p273`, and everything works perfectly fine on Ruby `2.1.3p242`.

I haven't changed anything on the project except Ruby version. The daemon stopped working after upgrade to Ruby 2.1.5.

**Comment by danlo** [comment] 2015-01-04 19:02
+1, I encountered this when upgrading from Rails 4.1.x to Rails 4.2. I traced it down to: net/smtp

Right before it sends the email

    # byebug break point
    b /usr/local/lib/ruby/2.1.0/net/smtp.rb:555
    c

Net Smtp id file (/usr/local/lib/ruby/2.1.0/net/smtp.rb:555)
    # $Id: smtp.rb 45111 2014-02-22 05:39:58Z naruse $

Actual code

    def do_start(helo_domain, user, secret, authtype)
      raise IOError, 'SMTP session already started' if @started
      if user or secret
        check_auth_method(authtype || DEFAULT_AUTH_TYPE)
        check_auth_args user, secret
      end
      s = Timeout.timeout(@open_timeout, Net::OpenTimeout) do
        tcp_socket(@address, @port)
      end
      logging "Connection opened: #{@address}:#{@port}"
      @socket = new_internet_message_io(tls? ? tlsconnect(s) : s)
      check_response critical { recv_response() }  # <--- recv_response() doesn't get anything; ERGO; time out.

**Comment by danlo** [comment] 2015-01-04 19:53
I think the error comes from EventMachine, since mailcatcher appears to rely on it for the majority of the Server IO issues.

**Comment by danlo** [comment] 2015-01-04 20:11
Forcing the mailcatcher to use 

gem 'eventmachine', '1.0.3' 

fixes the problem

**Comment by danlo** [comment] 2015-01-04 20:25
I solved the problem for myself by installing eventmachine 1.0.3

     gem install eventmachine -v 1.0.3
     gem uninstall eventmachine -v 1.0.4

and then restarting mailcatcher.

**Comment by juukie14** [comment] 2015-01-05 11:55
@danlo that worked for me too! :+1:

**Comment by samuelgbrown** [comment] 2015-01-05 16:08
@danlo +1, also fixed for me

**Comment by benjaminwood** [comment] 2015-01-05 17:16
Thanks @danlo, that does the trick!

**Comment by eikes** [comment] 2015-01-05 22:08
:+1: @danlo

**Comment by drmikecrowe** [comment] 2015-01-06 15:24
:+1: @danlo

**Comment by kyleries** [comment] 2015-01-07 01:07
:+1: @danlo

**Comment by chrishough** [comment] 2015-01-07 09:32
I am getting the same problem on osx 10.10.1, rails 4.2, and ruby 2.2.0.  I tried @danlo's fix but that tossed another huge error for me: 
```
➜  ~  gem install eventmachine -v 1.0.3
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/chrishough/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20150107-6357-13us0t8.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp:827:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/chrishough/.rbenv/versions/2.2.0/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:827:32: error: cannot initialize a parameter of type 'rb_fdset_t *' with an rvalue of type 'fd_set *'
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                      ^~~~~~~~
/Users/chrishough/.rbenv/versions/2.2.0/include/ruby-2.2.0/ruby/intern.h:454:42: note: passing argument to parameter here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                         ^
em.cpp:946:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/chrishough/.rbenv/versions/2.2.0/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
3 errors generated.
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.3/gem_make.out
```

**Comment by hube** [comment] 2015-01-08 07:12
:+1: @danlo

**Comment by Penderis** [comment] 2015-01-09 01:23
Thank you for this, hours of reading articles where it just all about port 1080 and no one cares about 1025. This helped save my sanity. @danlo

**Comment by davidochoa** [comment] 2015-01-12 11:55
:+1:  @danlo, thanks!

**Comment by klein0r** [comment] 2015-01-15 14:17
Nice solution @danlo ! Thanks!

**Comment by sj26** [comment] 2015-01-17 04:30
Seems to be a bug in the latest version of EventMachine, sadly. -.-

The reason it doesn't daemonise until after the eventmachine loop is running is so that port failures can be reported to the user.

I'll see what's going on upstream in eventmachine. But honestly eventmachine has become a major pain. May see if there's a feasible alternative, maybe even going back to the standard library with a custom select loop.

**Comment by BelkinaDasha** [comment] 2015-01-19 16:29
@danlo, Thank you soo much!

**Comment by alextakitani** [comment] 2015-01-21 16:17
@danlo, Thank you!!!

**Comment by danlo** [comment] 2015-01-23 16:49
@sj26 Someone mentioned on another thread; but could we have a new release of the existing code, but just forcing event machine at 1.0.3?

**Comment by davidahopp** [comment] 2015-01-26 19:25
Just tested this myself, when mailcatcher -v 0.5.12 is running with eventmachine -v 1.0.4 the timeout happens.

Note: mailcatcher -v 0.5.12 does not install eventmachine -v 1.0.4, something else in your project is what is causing the 1.0.4 version to be installed. So this can also be fixed by forcing your project to install 1.0.3 and then uninstalling the 1.0.4 version.

**Comment by davidahopp** [comment] 2015-01-26 19:41
I issued a pull request as a temporary fix that forces the version of eventmachine to be less than 1.0.4. If that is not used, eventmachine will default install 1.0.4 which will cause the timeout issue

**Comment by sj26** [comment] 2015-01-27 21:54
This does seem to be an eventmachine regression.

Please try [mailcatcher 0.6.0pre1](https://rubygems.org/gems/mailcatcher/versions/0.6.0pre1) (`gem install mailcatcher --pre`) which restricts eventmachine to != 1.0.4.

**Comment by felixbuenemann** [comment] 2015-01-28 19:15
@chrishough eventmachine 1.0.3 is not compatible with ruby 2.2, so you need to use ruby 2.1 or older.

**Comment by matthewbarram** [comment] 2015-01-29 01:20
I have the same issue. Running as `mailcatcher -f` works for me too.

**Comment by sj26** [comment] 2015-01-29 02:41
@matthewbarram please try mailcatcher 0.6.0pre1 (gem install mailcatcher --pre).

**Comment by JackEllis** [comment] 2015-01-29 03:35
@sj26 Just came to report this exact bug. Brought in the 0.0.0pre1, as you suggested, and I can now run it fine without --foreground - thank you :+1:

**Comment by sj26** [comment] 2015-01-29 10:58
This has been worked around in 0.6.0, please upgrade with `gem install mailcatcher`.

The root cause of this has also been lodged as an issue upstream:

https://github.com/eventmachine/eventmachine/issues/569

**Closed by sj26** 2015-01-29 10:58 UTC

**Comment by sj26** [comment] 2015-02-03 20:55
Ah, I see:

```
eventmachine (1.0.5)
```

They must have released a new version which has broken my fix. I'll look into it again.

**Comment by ianks** [comment] 2015-02-03 22:20
:+1:

**Comment by sj26** [comment] 2015-02-03 22:58
mailcatcher 0.6.1 is out which works with eventmachine up to 1.0.5, and restricts future upgrades.

**Comment by BrizzleRocker** [comment] 2015-02-04 09:16
@sj26 downloading now and will report back, many thanks for monitoring this, great response.

**Comment by BrizzleRocker** [comment] 2015-02-04 09:19
@sj26 It works! Thanks again for your timely update.

**Comment by sebasjimenez10** [comment] 2015-09-11 14:58
@danlo :+1:

**Comment by jmnewman** [comment] 2016-03-08 01:26
not sure if this is still open, but I am running into this problem where mailcatcher has stopped working. Nothing that I know of has changed (other than switching between a lot of branches) and I can't find any error messages showing where something might be breaking. right now in development I can see the emails being sent in the logs, but they're not popping up in mailcatcher. here's my set up

- Rails 4.2.6
- ruby 2.2.2p95
- mailcatcher 0.6.4

I have tried @danlo tip and it didn't work (ended with a result similar to @chrishough) and tried running with `mailcatcher -f -v` and installing `gem install mailcatcher --pre` and still am not getting it to work. are there any other workarounds?

**Comment by pedro-stanaka** [comment] 2016-04-21 02:30
I'm having the same problems as @jmnewman. 
Using
ruby 2.3.0p0 (with rvm)
mailcatcher 0.6.4
eventmachine 1.0.9.1
