### ISSUE TITLE
Internal Server Error when downloading messages.

### ISSUE THREAD

**Issue by sleitz** [sj26/mailcatcher#376] opened 2018-05-04 15:31 UTC
Version 0.6.5.

Web interface shows message nicely.

Only accessing http://127.0.0.1:1080/messages/1.json will lead to

    Internal Server Error

I read through #201 but that was way back and seems fixed.

What would have to be provided for a fix?

**Comment by sj26** [comment] 2018-05-05 00:00
:-(

Could you produce the full contents of the email send to mailcatcher which triggers the issue?

**Comment by takkyuuplayer** [comment] 2018-05-05 22:09
I have the same issue.

## How to reproduce

Boot mailcatcher.

```
$ mailcatcher --foreground --http-ip=0.0.0.0
Starting MailCatcher
==> smtp://127.0.0.1:1025
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://0.0.0.0:1080
```

In the other shell, run [sendmail\.rb](https://gist.github.com/takkyuuplayer/51ded7d475ef61e16391b9fdb5707ec1) and curl.


```
$ ruby sendemail.rb

$ curl http://localhost:1080/messages
[{"id":1,"sender":"<your@mail.address>","recipients":["<his_address@example.com>"],"subject":"test message","size":"217","created_at":"2018-05-05T21:47:24+00:00"}]%

$ curl http://localhost:1080/messages/1.json
<h1>Internal Server Error</h1>%
```

Log in the first shell

```
$ mailcatcher --foreground --http-ip=0.0.0.0
Starting MailCatcher
==> smtp://127.0.0.1:1025
/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://0.0.0.0:1080
==> SMTP: Received message from '<your@mail.address>' (217 bytes)
2018-05-05 18:00:34 - Encoding::UndefinedConversionError - "\xE3" from ASCII-8BIT to UTF-8:
        /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/json/common.rb:224:in `encode'
        /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/json/common.rb:224:in `generate'
        /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/json/common.rb:224:in `generate'
        /usr/local/lib/ruby/gems/2.5.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web/application.rb:94:in `block in <class:Application>'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/lib/ruby/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:66:in `block in call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `each'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:153:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web.rb:19:in `call'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
        /usr/local/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
        /usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
        /usr/local/lib/ruby/gems/2.5.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:173:in `run!'
        /usr/local/lib/ruby/gems/2.5.0/gems/mailcatcher-0.6.5/bin/mailcatcher:5:in `<top (required)>'
        /usr/local/bin/mailcatcher:23:in `load'
        /usr/local/bin/mailcatcher:23:in `<main>'
```

There is no problem when I see the mail's Source via web interface

```
From: Your Name <your@mail.address>
To: Destination Address <someone@example.com>
Subject: test message
Date: Sat, 23 Jun 2001 16:26:43 +0900
Message-Id: <unique.message.id.string@example.com>

UTF-8の文字列
```

## Environment

```
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
$ mailcatcher --version
mailcatcher 0.6.5
```

**Comment by sj26** [comment] 2018-05-07 01:01
Ah, if you're sending emails with UTF-8 and they are being transferred over the wire without any encoding then your SMTP library is broken. MailCatcher does not support the SMTP 8BIT extensions, and does not advertise that it does, because many SMTP servers don't either. Please make sure your message bodies are being encoded as quoted printable or something.

**Comment by takkyuuplayer** [comment] 2018-05-07 04:31
> Please make sure your message bodies are being encoded as quoted printable or something.

Thanks. I confirmed that mailcatcher's API works with `base64` or `quoted-printable` by [sendmail2.rb](https://gist.github.com/takkyuuplayer/51ded7d475ef61e16391b9fdb5707ec1#file-sendmail2-rb) and for 8bit, it will return internal server error.

**Comment by sleitz** [comment] 2018-05-07 06:41
This is my email:

    Date: Fri, 04 May 2018 15:24:09 +0000
    From: =?UTF-8?Q?Online-Veranstaltungskalender?= <noreply@localhost>
    To: max.mustermann@stadt.de
    Subject: =?UTF-8?Q?Neuer=20Eintrag=20im=20Online-Veranstaltungskalender?=
    MIME-Version: 1.0
    Content-Type: text/plain; charset="UTF-8"
    Content-Transfer-Encoding: 8bit
    
    Vielen Dank für Ihren Eintrag im Veranstaltungskalender. Sie haben folgende Daten angegeben:
    
    Anfang der Veranstaltung: 04.10.2018 10:00
    Ende der Veranstaltung: 04.10.2018 10:00
    Veranstalter: Evangelische Brüdergemeinde Pfaffenhofen
    Ort: Gemeindehaus
    Titel der Veranstaltung: To believe or not to believe?
    Beschreibung: Lorem Ipsum dolor sit amet.
    Kategorie: Glaube
    
    Ihr Team vom Veranstaltungskalender

The email is generated with a framework's email class, so I would guess it adheres to RFCs, though I'm no expert at that and can't validate it.

I'm running mailcatcher in a container, will have to see how to get the debugging output. I'll be back.

**Comment by sj26** [comment] 2018-05-07 07:06
@sleitz the message body looks good, but it's presuming a mail transport which supports 8 bit transfer:

```
Content-Transfer-Encoding: 8bit
```

This isn't always supported. The smtp transport responsible for sending the message should be negotiating the transfer encoding based on server capabilities, and throwing a sensible error when there is a mismatch, or re-encoding the message body. If it isn't then the framework has a bug.

**Comment by sleitz** [comment] 2018-05-07 07:16
Wow, you are fast! I'll deep-dive into Zend Framework and will have a look. So it seems it might not be a mailcatcher issue, shall we close this?

**Comment by sj26** [comment] 2018-05-07 08:49
Neat! Yeah, sounds like we should close here.

That said, I’m aware mailcatcher should be throwing more sensible errors or being more lenient with input. It’s an outstanding issue, but tracked separately.

**Closed by sj26** 2018-05-07 08:49 UTC
