### ISSUE TITLE
Request: Always show latest mail

### ISSUE THREAD

**Issue by mahemoff** [sj26/mailcatcher#394] opened 2019-04-15 12:01 UTC
It would be extremely useful if MailCatcher kept the browser synchronized with latest mail that's been received.

Is there any way to do this? If not, please consider it a request for a new option/action to always show latest. Then you can just keep the page open and don't have to interact with it to preview changes.

**Comment by her** [comment] 2019-04-29 23:27
@mahemoff what do you mean latest mail that's been received? 

Current behavior for me on macOS in Safari is that new mail is received without having to refresh the browser.

**Comment by sj26** [comment] 2019-04-29 23:33
I think you mean a “follow” mode, to always _select and render_ the latest mail when it is received as well as displaying it in the list? I like the idea, but implementation is going to be finicky. I’d really like to rewrite the mail catcher frontend to make it more resilient and make features like this easier.

**Comment by mahemoff** [comment] 2019-04-29 23:40
@sj26 Yes, that's it, while the list of mails may be updated automatically, a browser interaction is still needed to select and render the latest mail. Looking at mailcatcher.js, maybe it could be implemented just after `addMessage` in the websocket callback, ie simply a one-liner to switch to that message if a certain param is present in the URL.

**Comment by sj26** [comment] 2019-04-29 23:52
and a button to turn the behavior on/off, somewhere to store whether the behavior is on, an arg to start with that behavior, sensible auto-disable behavior (like selecting another message should probably disable follow) etc.

**Comment by sj26** [comment] 2021-02-22 23:08
This is a duplicate of #266, please track there.

**Closed by sj26** 2021-02-22 23:08 UTC
