### ISSUE TITLE
Request for monospace on plain-text body

### ISSUE THREAD

**Issue by GDmac** [sj26/mailcatcher#462] opened 2021-06-04 14:09 UTC
Thank you for a great tool to catch mail in development.
Would it be possible to set a formatting CSS style on the <body> element of the plaintext?

```
element.style {
    font-family: monospace;
    white-space: pre-wrap;
}
```

**Comment by sj26** [comment] 2021-06-07 04:29
I did this on purpose because most mail clients display plain text mail as regular text without fixed width fonts.

**Comment by GDmac** [comment] 2021-06-07 06:19
Can we at least have white-space: pre-wrap; then ?

**Comment by sj26** [comment] 2021-07-17 03:59
After a bit of poking around this does seem like a good idea. Fixed in e6f83976bbc93de88ddb9cf7179003ae1595c1a5.

**Closed by sj26** 2021-07-17 03:59 UTC

**Comment by GDmac** [comment] 2021-07-20 06:37
Whoo hoo 
![download](https://user-images.githubusercontent.com/156334/126273325-2372746b-02eb-4d36-b86f-6b11fd657102.png)

**Comment by sj26** [comment] 2021-07-20 09:18
To try it out in the latest beta:

```
gem install --pre mailcatcher
```

**Comment by GDmac** [comment] 2021-07-27 09:24
docker-compose
```
    mail:
        image: sj26/mailcatcher
        expose:
            - "1025"
        ports:
            - "1080:1080"
```   
Pulling mail (sj26/mailcatcher:)...
latest: Pulling from sj26/mailcatcher
...
Status: Downloaded newer image for sj26/mailcatcher:latest

cli: mailcatcher --version
mailcatcher 0.7.1

**Comment by sj26** [comment] 2021-07-27 09:40
Whoops, I forgot to bump latest, sorry! Try it again.

**Comment by GDmac** [comment] 2021-07-28 06:03
Tested (v.0.8.1), it's not working
```
<iframe class="body" data-flexie-id="3" data-flexie-parent="true" style="" src="/messages/1.plain">
  <html>
    <head></head>
      <body>
        Orderlist Supplier Foo
        <br>
        <br>
        Orderlist : 202 
        <br>
        Date : 2021-07-28 07:51:08
        <br>
        ...
```

**Comment by sj26** [comment] 2021-08-01 00:58
Weird! I can't replicate this. It's working fine on Safari, Firefox and Chrome for me when using latest MailCatcher v0.8.1.

Can you provide a reproduction case? Or more details?

**Comment by GDmac** [comment] 2021-08-02 08:18
Yes, it's working, css coming thru (probably container was hanging in there).
Thanks for the heads up.

All in all, without the monospace font still not optimal for me,
the sans-serif has to many width-changes for it to align.
(in my real mail-client i have set monospace for plain-text messages)

**Comment by sj26** [comment] 2021-08-03 01:59
Great!

I do appreciate that some folks may prefer monospace, but that's not a default in most mail clients, and so I don't think it shoud be a default here. It'd be nice to have a button for switching to monospace and back eventually, but that's likely to happen after a redo of the whole frontend (#473).
