### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by mikaelkundert** [sj26/mailcatcher#284] opened 2016-04-15 11:02 UTC
I have a use case where I'm trying to setup proxy to access Mailcatcher from specific URL address like www.example.com/mailcatch

When setting up proxy configuration in Apache, I was struggling to configure it easily without breaking CSS/JS links. I got it finally working, but it would have been easier if Mailcatcher would have been an option to set the base URL, so that the web interface can generate links according to the given base URL.

``$ mailcatcher --base-url BASE-URL   Sets the base URL for the web interface``

Example:
``$ mailcatcher --base-url https://example.com/mail/catcher``

**Comment by jkrehm** [comment] 2016-04-17 17:40
I'm looking to do the same thing. How did you make it work, if you don't mind sharing?

**Comment by mikaelkundert** [comment] 2016-04-19 11:46
Well after a while, I didn't get it completely working :(

**Comment by sj26** [comment] 2016-08-10 00:04
Ah, this is a duplicate of #227

**Closed by sj26** 2016-08-10 00:04 UTC
Labels: idea
