### ISSUE TITLE
Support for context paths

### ISSUE THREAD

**Issue by sean-abbott** [sj26/mailcatcher#227] opened 2015-05-26 21:39 UTC
So that you can put mailcatcher behind a reverse proxy easily.  This would make it much easier to use in staging environments, or shared test environments.

**Comment by fdrouet** [comment] 2015-10-21 05:37
that would be great !

**Comment by sj26** [comment] 2016-01-31 11:39
Nice idea.

**Comment by Baklap4** [comment] 2017-07-14 07:54
@sj26 How far is this away from being implemented? We'd love to have this so our containers behind traefic will work nicely again!

**Comment by andrewnicols** [comment] 2017-07-28 02:22
I've just been hitting the same issue - would be great to see a solution to this if possible!

**Comment by liamjones** [comment] 2017-07-29 10:32
If it's helpful for anyone else; until this is complete I've been working around it with an nginx container in my docker-compose setup that rewrites the responses using the following location config:

````
	location /mail {
		proxy_pass http://127.0.0.1:40130/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 1d;
		sub_filter 'src="/'     'src="/mail/';
		sub_filter 'href="/'    'href="/mail/';
		sub_filter 'url(/'      'url(/mail/';
		sub_filter '"/messages' '"/mail/messages';
		sub_filter_types text/html text/css application/javascript;
		sub_filter_once off;
	}
````

**Comment by andrewnicols** [comment] 2017-07-29 13:25
I just switched to MailHog. Just need the ProxyPass, ProxyReversePass, and a second ProxyPass for the websocket

**Comment by sj26** [comment] 2017-07-31 05:49
I just added an `--http-path` option so you can add `--http-path=/mailcatcher` to mount mailcatcher with a path prefix. This has been released as 0.7.0.beta1, so you can `gem install mailcatcher --pre`. Give it a go?

**Comment by jgrasl** [comment] 2017-10-31 17:15
Hi @sj26 . Awesome change. One thing seems to be not working for me tough. Every link changed to /mailcatcher except the attachment link for the mail. For me it's still goes to /messages/1/ instead of /mailcatcher/messages/1/.

**Comment by 1stone** [comment] 2018-05-09 15:45
I tried the new `http-path` option from 0.7.0.beta1.
When placed behind a reverse proxy, mapping `/mailcatcher` to `localhost:1080/mailcatcher` the UI and mail rendering looks fine.
However, I'm not able to "Clear" all messages. Clicking the button does show the confirmation popup, but if confirmed nothing happens.

**Comment by schmkr** [comment] 2018-10-04 13:48
FYI, here's the error you get when pressing the "clear" button:

```
mailcatcher.js:formatted:6014 Uncaught TypeError: Failed to construct 'URL': Invalid URL
```

Coming from https://github.com/sj26/mailcatcher/blob/605e94f4e816b197c6c622aa2ec1ef86de1db464/assets/javascripts/mailcatcher.js.coffee#L49

**Comment by paulggapps** [comment] 2020-04-08 11:02
Don't know if this helps, but we run mailcatcher on our staging servers and use a path instead of port 1080 i.e. domain.com/mc

We had everything working except attachments downloads, however, all other URLs were being correctly redirected to /mc/messages except attachment links.

Using the nginx config above by @liamjones we edited the following line and it now all works as expected:

```sub_filter_types *;```

**Comment by mullnerz** [comment] 2020-07-27 07:33
Mailcatcher uses websockets, so for attachments to work, you also need to filter application/json content:

`sub_filter_types text/html text/css application/javascript application/json;`

(So no need for `sub_filter_types *;`)

**Comment by sj26** [comment] 2021-02-22 23:07
`--http-path` in  0.7.0+ provides this feature.

**Closed by sj26** 2021-02-22 23:07 UTC
Labels: feature

**Comment by rajeshisnepali** [comment] 2022-01-11 08:21
> ```
> 	location /mail {
> 		proxy_pass http://127.0.0.1:40130/;
> 		proxy_http_version 1.1;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection "upgrade";
> 		proxy_read_timeout 1d;
> 		sub_filter 'src="/'     'src="/mail/';
> 		sub_filter 'href="/'    'href="/mail/';
> 		sub_filter 'url(/'      'url(/mail/';
> 		sub_filter '"/messages' '"/mail/messages';
> 		sub_filter_types text/html text/css application/javascript;
> 		sub_filter_once off;
> 	}
> ```

I got an error while running in Cloudflare with brotli compression **on**. 
```
root@s02:~# nginx -t                                                                                                                                                                                 
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/domain.conf:33
```

I had a different `--http-path`. From https://github.com/google/ngx_brotli/issues/104#issuecomment-661030168, I did
```
  location /bin {
        proxy_pass http://127.0.0.1:1081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 1d;
        sub_filter '"/messages' '"/bin/messages';
        sub_filter_types text/css application/javascript;
        sub_filter_once off;
 }
```
and was able to run properly
